microservice:
  name: service-dmeo-test
  port: 8080
  portName: service-invue-port
  replicaCount: 1
  serviceType: LoadBalancer
  container:
    image: platformcluster.azurecr.io/service-invue:latest
    port: 8080
  ssh:
    enabled: false
  secrets:
   - name: db-secret
     data:
      - key: "DB_PASSWORD"
        name: DB_PASSWORD
      - key: "DB_USER"
        name: DB_USER
      - key: DB_NAME
        value: DB_NAME
  externalSecrets: 
     - name: db-secret
       data:
        - key: "DB_PASSWORD"
          remoteKey: SERVICE-DB-PASSWORD
        - key: "DB_USER"
          remoteKey: SERVICE-DB-USERNAME
        - key: DB_NAME
          remoteKey: SERVICE-DB-NAME
  dapr:
    enabled: true
    appId: service-invue
    appPort: 8080
    enableApiLogging: true
    port: 3500
    portName: service-invue-dapr-sidecar-port