{{ if .Values.microservice.ssh.enabled}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.microservice.name }}-ssh-keys
data:
   LOCK_ENROLMENT_PVT_KEY: {{ .Values.microservice.ssh.lockEnrollmentPrivateKey | b64enc }}
   ROOT_PRIVATE_KEY: {{ .Values.microservice.ssh.rootPrivateKey | b64enc }}
   ROOT_PUBLIC_KEY:  {{ .Values.microservice.ssh.rootPublicKey | b64enc  }}
  {{ end }}